const updated="4 October 2026";const blocks=[
["1. Who operates Asanib",["Asanib is operated by JS Ventures LLC in the United Arab Emirates. References to “Asanib”, “we”, “us” or “our” in this policy refer to the Asanib service operated by JS Ventures LLC."]],
["2. Information we collect",["We may collect account information such as email address, name and contact details; order and delivery information such as requested items, merchants, delivery addresses, notes and phone numbers; storefront activity such as cart contents and product selections; booking, payment-reference and order-status information; and provider or merchant information needed to operate listings and fulfil orders.","Customers should avoid putting unnecessary sensitive personal information into order notes or request descriptions."]],
["3. Location and delivery information",["Asanib uses delivery addresses and related location details to fulfil local pickup and delivery requests. Depending on how the service evolves, mapping or address-standardisation providers may also process location data needed to improve address accuracy and routing."]],
["4. Merchant and provider information",["Merchants and providers may supply business details, catalogue information, service areas, contact details and other information necessary to appear on Asanib or fulfil customer orders. Where business-verification documents are requested, access should be restricted to authorised personnel and used for verification, fraud prevention, support and compliance purposes."]],
["5. Payments",["Where Asanib Checkout is available, the payment interface is provided by Ziina and the payment is processed through the Ziina Business account used by JS Ventures LLC for Asanib. Payment-card details entered into Ziina are processed by Ziina and are not stored by Asanib. Asanib may retain payment-intent references, payment status, amounts and related order records so the platform can confirm whether an order has been paid.","If a merchant or provider later offers an approved external checkout destination, that destination and its payment processor will handle payment information under their own terms and privacy practices."]],
["6. How we use information",["We use information to operate accounts, display merchant listings and products, process carts and orders, calculate or present order totals, coordinate delivery, facilitate available payment options, send transactional communications, prevent abuse, provide customer support, resolve disputes and improve the reliability of Asanib."]],
["7. Sharing",["Customer order details are shared only as reasonably necessary with merchants, providers, delivery partners and other parties involved in fulfilment. Merchant or provider details may be shown to customers as part of storefront listings or order fulfilment.","We may use infrastructure and service providers such as Supabase, Vercel, Cloudflare and Ziina to operate the platform. They process relevant data according to their own terms and our configuration."]],
["8. Browser storage, cart and sessions",["Asanib uses essential browser storage and authentication/session technologies to keep users signed in, maintain carts, secure requests and support core app functionality. Cart data may be stored locally in the browser until it is cleared, replaced or converted into an order."]],
["9. Data retention and security",["We retain information for as long as reasonably necessary to operate the service, maintain business and payment records, resolve disputes, prevent fraud and meet legal obligations. We use reasonable technical and organisational measures to protect information, but no online system can guarantee absolute security."]],
["10. Your choices and rights",["You may stop using Asanib at any time. You may contact us to request access, correction or deletion of eligible personal information where permitted by applicable law and where retention is not required for legitimate operational, payment, fraud-prevention, dispute or legal-record purposes."]],
["11. Contact",["Privacy and support requests relating to Asanib should be directed to JS Ventures LLC through the contact details published in the Asanib service."]]
];export default function Page(){return <main className="legal-shell"><p className="eyebrow">LEGAL · UPDATED {updated.toUpperCase()}</p><h1>Privacy Policy</h1><p>This Privacy Policy explains how Asanib collects, uses and protects information when customers, merchants and service providers use the platform.</p>{blocks.map(([h,ps])=><section key={h as string}><h2>{h}</h2>{(ps as string[]).map(p=><p key={p}>{p}</p>)}</section>)}<p className="legal-note">These platform policies describe Asanib’s current operating model and do not replace rights or obligations imposed by applicable law.</p></main>}