const updated="4 October 2026";const blocks=[
["1. Operator and platform role",["Asanib is operated by JS Ventures LLC in the United Arab Emirates. Asanib is a technology platform for local commerce, pickup, delivery and service requests. It can allow customers to request items or services, browse participating merchants, place storefront orders and manage payment and fulfilment.","Unless expressly stated otherwise for a specific transaction, third-party merchants and providers remain responsible for the products or services they supply. Asanib does not become the manufacturer, merchant or service provider merely by facilitating a listing, request, order, booking, payment interface or delivery arrangement."]],
["2. Accounts and eligibility",["Users must provide accurate information and keep account credentials secure. Merchant or provider accounts may require business verification before listings or fulfilment access is enabled. Asanib may refuse, suspend or remove accounts where reasonably necessary for safety, misuse, fraud, legal compliance or platform integrity."]],
["3. Customer requests and storefront orders",["Customers must describe requests accurately and lawfully. Storefront customers are responsible for checking product information, quantities, delivery details and the total shown before payment. Requests must not seek illegal, unsafe or prohibited goods or services."]],
["4. Merchant and provider responsibilities",["Merchants and providers are responsible for maintaining accurate listings, prices, stock status, business information, licences, permits and fulfilment details where applicable. They are responsible for the quality, legality and safe supply of their products or services, subject to applicable law."]],
["5. Prices, carts, quotes and payment",["A cart or displayed product price does not guarantee availability until the order is accepted or fulfilled. For custom pickup requests, quoted totals may include item allowance, delivery, service and payment-related fees as presented before checkout.","Where Asanib Checkout is available, Ziina provides the payment interface and JS Ventures LLC receives the customer payment through its Ziina Business account for the Asanib order. Asanib records payment status and references against the order. Merchant or provider settlement is handled separately from the customer checkout flow."]],
["6. Delivery and fulfilment",["Delivery availability and timing depend on merchant or provider readiness, pickup location, destination, courier availability and order requirements. Estimated times are not guaranteed unless expressly stated otherwise. Customers must provide accurate delivery and contact information and remain reachable where needed for fulfilment."]],
["7. Cancellations, disputes and refunds",["Refund responsibility depends on the payment method and transaction circumstances. Where payment was made through Asanib Checkout, JS Ventures LLC may process an eligible refund or reversal through Ziina where available, subject to the order circumstances, merchant or provider position, applicable law and payment-processor rules.","Asanib may assist using platform records or communications, but this does not guarantee a particular dispute outcome."]],
["8. Communications",["Users may receive transactional communications needed to operate the service, including order, booking, payment, delivery and account notifications."]],
["9. Acceptable use",["Do not interfere with the platform, impersonate others, submit fraudulent requests or orders, misuse contact information, scrape protected data, circumvent security controls or use Asanib to facilitate unlawful activity."]],
["10. Availability and liability",["We aim to keep Asanib reliable but do not guarantee uninterrupted availability, continuous merchant stock or that every request can be fulfilled. To the extent permitted by applicable law, JS Ventures LLC is not responsible for losses caused solely by the independent acts or omissions of third-party merchants, providers or delivery partners. Nothing in these terms excludes rights or liabilities that cannot legally be excluded."]],
["11. Changes",["We may update these terms as Asanib evolves. The updated date will be shown on this page. Continued use after an update may constitute acceptance where permitted by law."]]
];export default function Page(){return <main className="legal-shell"><p className="eyebrow">LEGAL · UPDATED {updated.toUpperCase()}</p><h1>Terms &amp; Conditions</h1><p>These Terms &amp; Conditions govern access to and use of Asanib by customers, merchants, service providers and other users.</p>{blocks.map(([h,ps])=><section key={h as string}><h2>{h}</h2>{(ps as string[]).map(p=><p key={p}>{p}</p>)}</section>)}<p className="legal-note">These terms describe Asanib’s current operating model and do not remove rights that apply under applicable law.</p></main>}